<?xml version="1.0" encoding="utf-8"?>
<testsuites><testsuite name="django_jenkins.tasks.lettuce_tests.LettuceTestCase"><testcase classname="django_jenkins.tasks.lettuce_tests.LettuceTestCase" name="runTest" time="0.030377"><error message="'module' object has no attribute 'DEFAULT_EXCLUDE'">Traceback (most recent call last):
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/django_jenkins/tasks/lettuce_tests.py", line 64, in runTest
    result = self.runner.run()
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/lettuce/__init__.py", line 137, in run
    self.loader.find_and_load_step_definitions()
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/lettuce/fs.py", line 49, in find_and_load_step_definitions
    module = __import__(to_load)
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/django_jenkins/tasks/run_pep8.py", line 13, in &lt;module&gt;
    class Task(BaseTask):
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/django_jenkins/tasks/run_pep8.py", line 17, in Task
    default=pep8.DEFAULT_EXCLUDE + ",migrations",
AttributeError: 'module' object has no attribute 'DEFAULT_EXCLUDE'
</error></testcase><testcase classname="django_jenkins.tasks.lettuce_tests.LettuceTestCase" name="runTest" time="5.290343"><error message="teardown_environment() takes no arguments (1 given)">Traceback (most recent call last):
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/django_jenkins/tasks/lettuce_tests.py", line 64, in runTest
    result = self.runner.run()
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/lettuce/__init__.py", line 183, in run
    call_hook('after', 'all', total)
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/lettuce/registry.py", line 88, in call_hook
    callback(*args, **kw)
TypeError: teardown_environment() takes no arguments (1 given)
</error><system-out>========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

</system-out><system-err>Traceback (most recent call last):
  File "/home/carlos/.virtualenvs/django/local/lib/python2.7/site-packages/lettuce/registry.py", line 88, in call_hook
    callback(*args, **kw)
TypeError: teardown_environment() takes no arguments (1 given)
</system-err></testcase></testsuite></testsuites>